### ISSUE TITLE
Error when launching filtering analysis

### ISSUE THREAD

**Issue by Oodnadatta** [REGOVAR/Regovar#79]
```
QUERY: SELECT d.uid AS duid, d.reference_id AS ref, d.version, d.ord AS dord, d.name_ui AS dname, d.description AS ddesc, d.update_date AS ddate, a.uid AS fuid, a.name_ui AS name, a.ord AS ford, a.type AS type, a.description AS desc, a.meta AS meta                  FROM annotation_field a                  INNER JOIN annotation_database d ON a.database_uid=d.uid                  ORDER BY d.uid, a.ord...
2018-06-21 11:08:38,957 | [Error_ff45d9c5-d395-4133-ba2a-6e2cae2826db.log] Filtering error
2018-06-21 11:08:38,958 | -----------------------------
2018-06-21 11:08:38,958 | Traceback (most recent call last):
2018-06-21 11:08:38,958 |   File "/home/asdp/Tools/regovar/Regovar/regovar/api_rest/handlers/analysis_handler.py", line 135, in filtering
    result = await core.filters.request(int(analysis_id), filter_json, fields, order, variant_id, int(limit), int(offset))
2018-06-21 11:08:38,958 |   File "/usr/lib/python3.5/asyncio/coroutines.py", line 105, in __next__
    return self.gen.send(None)
2018-06-21 11:08:38,958 |   File "/home/asdp/Tools/regovar/Regovar/regovar/core/managers/filter_manager.py", line 966, in request
    "error_message": "Import of the sample () for the analysis {} are in progress.".format(", ".join(in_samples["loading"]), analysis.id),
2018-06-21 11:08:38,958 | TypeError: sequence item 0: expected str instance, int found
2018-06-21 11:08:38,958 | =============================
2018-06-21 11:08:39,171 | [Error_a467f994-8ac8-43f8-9119-cd6e3c98b81c.log] Filtering error
2018-06-21 11:08:39,171 | -----------------------------
2018-06-21 11:08:39,172 | Traceback (most recent call last):
2018-06-21 11:08:39,172 |   File "/home/asdp/Tools/regovar/Regovar/regovar/api_rest/handlers/analysis_handler.py", line 135, in filtering
    result = await core.filters.request(int(analysis_id), filter_json, fields, order, variant_id, int(limit), int(offset))
2018-06-21 11:08:39,172 |   File "/usr/lib/python3.5/asyncio/coroutines.py", line 105, in __next__
    return self.gen.send(None)
2018-06-21 11:08:39,172 |   File "/home/asdp/Tools/regovar/Regovar/regovar/core/managers/filter_manager.py", line 966, in request
    "error_message": "Import of the sample () for the analysis {} are in progress.".format(", ".join(in_samples["loading"]), analysis.id),
2018-06-21 11:08:39,172 | TypeError: sequence item 0: expected str instance, int found
2018-06-21 11:08:39,172 | =============================
```

**Comment by ikit** [comment]
Fix: Should not crash anymore, if sample are still importing, the analysis wait without raising exception
