### ISSUE TITLE
Non critical error when starting Regovar server

### ISSUE THREAD

**Issue by Oodnadatta** [REGOVAR/Regovar#80]
```
Error handling request
Traceback (most recent call last):
  File "/home/asdp/Tools/regovar/Regovar/venv/lib/python3.5/site-packages/aiohttp/web_protocol.py", line 385, in start
    resp = await self._request_handler(request)
  File "/usr/lib/python3.5/asyncio/coroutines.py", line 105, in __next__
    return self.gen.send(None)
  File "/home/asdp/Tools/regovar/Regovar/venv/lib/python3.5/site-packages/aiohttp/web_app.py", line 338, in _handle
    resp = await handler(request)
  File "/usr/lib/python3.5/asyncio/coroutines.py", line 105, in __next__
    return self.gen.send(None)
  File "/home/asdp/Tools/regovar/Regovar/venv/lib/python3.5/site-packages/aiohttp/web_middlewares.py", line 88, in impl
    return await handler(request)
  File "/usr/lib/python3.5/asyncio/coroutines.py", line 105, in __next__
    return self.gen.send(None)
  File "/home/asdp/Tools/regovar/Regovar/venv/lib/python3.5/site-packages/aiohttp_session/__init__.py", line 133, in factory
    response = await handler(request)
  File "/usr/lib/python3.5/asyncio/coroutines.py", line 105, in __next__
    return self.gen.send(None)
  File "/home/asdp/Tools/regovar/Regovar/venv/lib/python3.5/site-packages/aiohttp/web_urldispatcher.py", line 109, in handler_wrapper
    result = old_handler(*args, **kwargs)
  File "/home/asdp/Tools/regovar/Regovar/regovar/api_rest/handlers/file_handler.py", line 180, in tus_upload_resume
    return tus_manager.resume(request)
  File "/home/asdp/Tools/regovar/Regovar/regovar/core/framework/tus.py", line 101, in resume
    fw = TusFileWrapper.from_request(request)
  File "/home/asdp/Tools/regovar/Regovar/regovar/core/framework/tus.py", line 61, in from_request
    return TusManager.route_maping[k](id)
  File "/home/asdp/Tools/regovar/Regovar/regovar/api_rest/handlers/file_handler.py", line 52, in __init__
    raise RegovarException("TUS File wrapper init error : Unknow id: {}".format(id))
core.framework.common.RegovarException: ERROR E000000 - TUS File wrapper init error : Unknow id: 6
```

**Comment by Arkanosis** [comment]
This is because the client [tries to resume non-finished uploads](https://github.com/REGOVAR/QRegovar/blob/feb1ac07ca167c03ac296208c5618b1c5d1c2623/app/Model/file/tusuploader.cpp#L172) on startup, and in your custom setup, some of them have been manually suppressed in PostgreSQL, making the server [unable to retrieve them](https://github.com/REGOVAR/Regovar/blob/1f3852c9b658a82c598f8b6dcd4b6bb649d48ad4/regovar/api_rest/handlers/file_handler.py#L43).

Manual changes to the database are not supported. However, the server shouldn't log “errors” like if they were its, when these “errors” are only bogus requests from the client. I suggest we only log them, without the full stack (and replace “error” by “warning”).
